/* Automatically generated by wasm2c */
#ifndef CHECKERS_WASM_H_GENERATED_
#define CHECKERS_WASM_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Z_checkers_init(void);
void Z_checkers_free(void);

/* export: 'indexForPosition' */
extern u32 (*Z_checkersZ_indexForPosition)(u32, u32);
/* export: 'offsetForPosition' */
extern u32 (*Z_checkersZ_offsetForPosition)(u32, u32);
/* export: 'isCrowned' */
extern u32 (*Z_checkersZ_isCrowned)(u32);
/* export: 'isWhite' */
extern u32 (*Z_checkersZ_isWhite)(u32);
/* export: 'isBlack' */
extern u32 (*Z_checkersZ_isBlack)(u32);
/* export: 'withCrown' */
extern u32 (*Z_checkersZ_withCrown)(u32);
/* export: 'withoutCrown' */
extern u32 (*Z_checkersZ_withoutCrown)(u32);
/* export: 'setPiece' */
extern void (*Z_checkersZ_setPiece)(u32, u32, u32);
/* export: 'getPiece' */
extern u32 (*Z_checkersZ_getPiece)(u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* CHECKERS_WASM_H_GENERATED_ */
