/* Automatically generated by wasm2c */
#ifndef CHECKERS_WASM_H_GENERATED_
#define CHECKERS_WASM_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif


/* import: 'events' 'piecemoved' */
extern void (*Z_eventsZ_piecemoved)(u32, u32, u32, u32);
/* import: 'events' 'piececrowned' */
extern void (*Z_eventsZ_piececrowned)(u32, u32);
void Z_checkers_init(void);
void Z_checkers_free(void);

/* export: 'indexForPosition' */
extern u32 (*Z_checkersZ_indexForPosition)(u32, u32);
/* export: 'offsetForPosition' */
extern u32 (*Z_checkersZ_offsetForPosition)(u32, u32);
/* export: 'isCrowned' */
extern u32 (*Z_checkersZ_isCrowned)(u32);
/* export: 'isWhite' */
extern u32 (*Z_checkersZ_isWhite)(u32);
/* export: 'isBlack' */
extern u32 (*Z_checkersZ_isBlack)(u32);
/* export: 'withCrown' */
extern u32 (*Z_checkersZ_withCrown)(u32);
/* export: 'withoutCrown' */
extern u32 (*Z_checkersZ_withoutCrown)(u32);
/* export: 'getTurnOwner' */
extern u32 (*Z_checkersZ_getTurnOwner)(void);
/* export: 'toggleTurnOwner' */
extern void (*Z_checkersZ_toggleTurnOwner)(void);
/* export: 'setTurnOwner' */
extern void (*Z_checkersZ_setTurnOwner)(u32);
/* export: 'isPlayersTurn' */
extern u32 (*Z_checkersZ_isPlayersTurn)(u32);
/* export: 'setPiece' */
extern void (*Z_checkersZ_setPiece)(u32, u32, u32);
/* export: 'getPiece' */
extern u32 (*Z_checkersZ_getPiece)(u32, u32);
/* export: 'move' */
extern u32 (*Z_checkersZ_move)(u32, u32, u32, u32);
/* export: 'shouldCrown' */
extern u32 (*Z_checkersZ_shouldCrown)(u32, u32);
/* export: 'crownPiece' */
extern void (*Z_checkersZ_crownPiece)(u32, u32);
/* export: 'distance' */
extern u32 (*Z_checkersZ_distance)(u32, u32);
/* export: 'initBoard' */
extern void (*Z_checkersZ_initBoard)(void);
/* export: 'memory' */
extern wasm_rt_memory_t (*Z_checkersZ_memory);

#ifdef __cplusplus
}
#endif

#endif  /* CHECKERS_WASM_H_GENERATED_ */
