[package]
name = "maturin_test"
version = "0.1.0"
edition = "2021"

[lib]
name = "maturin_test"
crate-type = ["cdylib"]

[dependencies]
thiserror = "1.0.0"
anyhow = "1.0.51"
pyo3 = { version = "0.15.1", features = ["extension-module"] }