[package]
name = "yewcounter"
version = "0.1.0"
# edition = "2021"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb="0.4.20"
yew="0.19.3"          # v0.4 used in book, ConsoleService removed in v0.19.x https://yew.rs/docs/next/migration-guides/yew/from-0_18_0-to-0_19_0
gloo-console="0.2.1"  # Replacement for ConsoleService
