## Source: https://raw.githubusercontent.com/thedodd/trunk/master/Trunk.toml
## An example Trunk.toml with all possible fields along with their defaults.

[build]
target = "index.html"  # The index HTML file to drive the bundling process.
release = false        # Build in release mode.
dist = "dist"          # The output dir for all final assets.
public_url = "/"       # The public URL from which assets are to be served.
filehash = true        # Whether to include hash values in the output file names.

[watch]
watch  = []
ignore = []

[serve]
address = "127.0.0.1"  # The address to serve on.
port = 8080            # The port to serve on.
open = true            # Open a browser tab once the initial build is complete.
no_autoreload = false  # Disable auto-reload of the web app.

[clean]
dist = "dist"  # The output dir for all final assets.
cargo = true   # Optionally perform a cargo clean.


[[hooks]]
stage = "build"
command = "./grass.sh"
command_arguments = []
