[package]
name = "maths"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
cached = "0.36.0"
spfunc = "0.1.0"
cauchy = "0.4.0"